name: 'stabilityai_client'
version: '1.0.2'
description: 'A server and browser based Stability.ai REST client allowing the generation and manipulation of images from text prompts.'
repository: https://github.com/shamblett/stabilityai_client
homepage: https://github.com/shamblett/stabilityai_client

funding:
  - https://www.darticulate.com/#funding
  
environment:
  sdk: '>=3.0.0 <4.0.0'

  
dependencies:
  async: '^2.12.0'
  http_parser: '^4.1.2'
  intl: '^0.20.1'
  meta: '^1.16.0'
  web: '^1.1.0'
  
dev_dependencies:
  test: '^1.25.14'
  lints: '^5.1.1'
  build_runner: '^2.4.14'
  build_test: '^2.2.3'
  build_web_compilers: '^4.0.9'
